### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by sanderboom** [bogdanteodoru/brunch-js-minify-js-files#1]
I like the idea of your brunch module, but noticed it's not avaiable via the npm registry. Could you explain how to integrate this with an existing brunch config? I've added the setting `minifyJsFiles` to the `plugins` section of `brunch-config.js` after cloning the repo in `node_modules` and running `npm install`. 

`brunch b -P` still leaves me with full blown js files. Any suggestion?

**Comment by sanderboom** [comment]
BTW I've published your module to the npm registry, as we could not install from git from behind the proxy :/ You might want to own this package, please let me know. See: https://www.npmjs.com/package/brunch-js-minify-js-files

**Comment by bogdanteodoru** [comment]
Sure, my username is bogdanteodoru

**Comment by sanderboom** [comment]
Done! It's yours
